import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import sharp from 'sharp';
import { createApp, prepare } from './app.js';
import { prisma } from './db/prisma.js';

const app = createApp();
async function clean(){ await prisma.savedPuzzleState.deleteMany(); await prisma.puzzlePiece.deleteMany(); await prisma.generatedPuzzle.deleteMany(); await prisma.puzzleConfiguration.deleteMany(); await prisma.puzzleProject.deleteMany(); await prisma.imageUpload.deleteMany(); await prisma.authSession.deleteMany(); await prisma.userAccount.deleteMany(); }
async function signup(email:string){ const agent=request.agent(app); const res=await agent.post('/api/auth/register').send({email,password:'Passwort123!',displayName:'User '+email.split('@')[0]}); assert.equal(res.status,201); return agent; }
async function uploadImage(agent: any){ const img=await sharp({create:{width:640,height:480,channels:3,background:'#7c3aed'}}).png().toBuffer(); const up=await agent.post('/api/images/upload').attach('image',img,{filename:'bergsee.png',contentType:'image/png'}); assert.equal(up.status,201); return up.body.image.id as string; }

test('healthcheck returns ok', async()=>{ await prepare(); const res=await request(app).get('/health'); assert.equal(res.status,200); assert.equal(res.body.ok,true); });

test('register validation returns clear 400 instead of server error', async()=>{ await clean(); const res=await request(app).post('/api/auth/register').send({email:'kein-email',password:'kurz',displayName:'A'}); assert.equal(res.status,400); assert.equal(res.body.error.message,'Ungültige Eingaben'); assert.ok(Array.isArray(res.body.error.issues)); });

test('register login me logout flow uses httpOnly session', async()=>{ await clean(); const agent=await signup('a@example.de'); const me=await agent.get('/api/auth/me'); assert.equal(me.status,200); assert.equal(me.body.user.email,'a@example.de'); const out=await agent.post('/api/auth/logout'); assert.equal(out.status,200); const after=await agent.get('/api/auth/me'); assert.equal(after.status,401); const login=await agent.post('/api/auth/login').send({email:'a@example.de',password:'Passwort123!'}); assert.equal(login.status,200); });

test('private upload generate progress and ownership isolation', async()=>{ await clean(); const a=await signup('owner@example.de'); const b=await signup('other@example.de'); const imageId=await uploadImage(a); const gen=await a.post('/api/puzzles/generate').send({imageId,title:'Bergsee',rows:3,columns:4,difficulty:'medium',pieceShape:'classic',visibility:'private'}); assert.equal(gen.status,201); assert.equal(gen.body.project.generated.pieces.length,12); const projectId=gen.body.project.id; const denied=await b.get(`/api/puzzles/${projectId}`); assert.equal(denied.status,404); const save=await a.put(`/api/puzzles/${projectId}/progress`).send({snapshot:{pieces:{x:{x:1,y:2,rotation:90}},zoom:1.1,timerSeconds:12},progressPercent:25}); assert.equal(save.status,200); const load=await a.get(`/api/puzzles/${projectId}/progress`); assert.equal(load.status,200); assert.equal(load.body.progress.progressPercent,25); });

test('public puzzles are visible to other users with independent progress', async()=>{ await clean(); const a=await signup('pub-owner@example.de'); const b=await signup('pub-player@example.de'); const imageId=await uploadImage(a); const gen=await a.post('/api/puzzles/generate').send({imageId,title:'Public Bergsee',rows:2,columns:2,difficulty:'easy',pieceShape:'classic',visibility:'public'}); assert.equal(gen.status,201); assert.equal(gen.body.project.visibility,'public'); const projectId=gen.body.project.id; const readByB=await b.get(`/api/puzzles/${projectId}`); assert.equal(readByB.status,200); assert.equal(readByB.body.project.title,'Public Bergsee'); assert.equal(readByB.body.project.savedState,undefined); const saveB=await b.put(`/api/puzzles/${projectId}/progress`).send({snapshot:{pieces:{p1:{x:10,y:20,rotation:-15}},zoom:1,timerSeconds:5},progressPercent:50}); assert.equal(saveB.status,200); const ownerProgress=await a.get(`/api/puzzles/${projectId}/progress`); assert.equal(ownerProgress.status,200); assert.equal(ownerProgress.body.progress.progressPercent,0); const bProgress=await b.get(`/api/puzzles/${projectId}/progress`); assert.equal(bProgress.body.progressPercent,undefined); assert.equal(bProgress.body.progress.progressPercent,50); });

test('only owners can change visibility and private puzzles disappear from other accounts', async()=>{ await clean(); const owner=await signup('visibility-owner@example.de'); const player=await signup('visibility-player@example.de'); const imageId=await uploadImage(owner); const gen=await owner.post('/api/puzzles/generate').send({imageId,title:'Sichtbarkeitstest',rows:2,columns:2,difficulty:'easy',pieceShape:'classic',visibility:'public'}); assert.equal(gen.status,201); const projectId=gen.body.project.id; const deniedPatch=await player.patch(`/api/puzzles/${projectId}`).send({visibility:'private'}); assert.equal(deniedPatch.status,404); const playerList=await player.get('/api/puzzles'); assert.equal(playerList.status,200); assert.ok(playerList.body.projects.some((p:any)=>p.id===projectId)); const hidden=await owner.patch(`/api/puzzles/${projectId}`).send({visibility:'private'}); assert.equal(hidden.status,200); assert.equal(hidden.body.project.visibility,'private'); const deniedRead=await player.get(`/api/puzzles/${projectId}`); assert.equal(deniedRead.status,404); const playerListAfter=await player.get('/api/puzzles'); assert.equal(playerListAfter.status,200); assert.ok(!playerListAfter.body.projects.some((p:any)=>p.id===projectId)); const visibleAgain=await owner.patch(`/api/puzzles/${projectId}`).send({visibility:'public',title:'Wieder öffentlich'}); assert.equal(visibleAgain.status,200); assert.equal(visibleAgain.body.project.visibility,'public'); assert.equal(visibleAgain.body.project.title,'Wieder öffentlich'); const allowedAgain=await player.get(`/api/puzzles/${projectId}`); assert.equal(allowedAgain.status,200); assert.equal(allowedAgain.body.project.title,'Wieder öffentlich'); });
