import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../db/prisma.js';
import { requireAuth } from '../middleware/auth.js';
import { generatePuzzle } from '../services/puzzleGeneratorService.js';
import { publicFilePath } from '../services/storageService.js';
const router=Router(); router.use(requireAuth);
const includeAll={ image:true, configuration:true, generated:{ include:{ pieces:true } }, savedState:true } as const;
function serialize(p:any){ if(!p) return p; return { ...p, image:p.image?{...p.image,url:publicFilePath(p.image.storagePath)}:undefined, generated:p.generated?{...p.generated,previewUrl:publicFilePath(p.generated.previewPath), pieces:p.generated.pieces?.map((x:any)=>({...x,url:publicFilePath(x.imagePath)}))}:undefined }; }
router.post('/generate', async (req,res,next)=>{ try{ const input=z.object({imageId:z.string(),title:z.string().min(1).optional(),rows:z.number().int().min(2).max(20).default(4),columns:z.number().int().min(2).max(20).default(4),difficulty:z.string().default('medium'),pieceShape:z.string().default('classic')}).parse(req.body); const project=await generatePuzzle(req.user!.id,{...input,title:input.title ?? 'Neues Puzzle'}); res.status(201).json({ project:serialize(project) }); }catch(e){next(e);} });
router.get('/', async (req,res,next)=>{ try{ const projects=await prisma.puzzleProject.findMany({where:{ownerId:req.user!.id}, orderBy:{updatedAt:'desc'}, include:includeAll}); res.json({ projects:projects.map(serialize) }); }catch(e){next(e);} });
router.get('/recent', async (req,res,next)=>{ try{ const projects=await prisma.puzzleProject.findMany({where:{ownerId:req.user!.id}, orderBy:[{lastOpenedAt:'desc'},{updatedAt:'desc'}], take:4, include:includeAll}); res.json({ projects:projects.map(serialize) }); }catch(e){next(e);} });
router.get('/:id', async (req,res,next)=>{ try{ const p=await prisma.puzzleProject.findFirst({where:{id:req.params.id,ownerId:req.user!.id}, include:includeAll}); if(!p) throw Object.assign(new Error('Puzzle nicht gefunden'),{status:404}); await prisma.puzzleProject.update({where:{id:p.id},data:{lastOpenedAt:new Date()}}); res.json({ project:serialize(p) }); }catch(e){next(e);} });
router.get('/:id/status', async (req,res,next)=>{ try{ const p=await prisma.puzzleProject.findFirst({where:{id:req.params.id,ownerId:req.user!.id}, select:{id:true,status:true}}); if(!p) throw Object.assign(new Error('Puzzle nicht gefunden'),{status:404}); res.json(p); }catch(e){next(e);} });
router.get('/:id/download', async (req,res,next)=>{ try{ const p=await prisma.puzzleProject.findFirst({where:{id:req.params.id,ownerId:req.user!.id}, include:{generated:true}}); if(!p?.generated) throw Object.assign(new Error('Puzzle nicht gefunden'),{status:404}); res.download(p.generated.previewPath); }catch(e){next(e);} });
router.delete('/:id', async (req,res,next)=>{ try{ const p=await prisma.puzzleProject.findFirst({where:{id:req.params.id,ownerId:req.user!.id}}); if(!p) throw Object.assign(new Error('Puzzle nicht gefunden'),{status:404}); await prisma.puzzleProject.delete({where:{id:p.id}}); res.json({ok:true}); }catch(e){next(e);} });
router.get('/:id/progress', async (req,res,next)=>{ try{ const p=await prisma.puzzleProject.findFirst({where:{id:req.params.id,ownerId:req.user!.id}, include:{savedState:true}}); if(!p) throw Object.assign(new Error('Puzzle nicht gefunden'),{status:404}); res.json({ progress:p.savedState?{...p.savedState,snapshot:JSON.parse(p.savedState.snapshotJson)}:null }); }catch(e){next(e);} });
async function saveProgress(req:any,res:any,next:any){ try{ const body=z.object({ snapshot:z.any(), progressPercent:z.number().min(0).max(100) }).parse(req.body); const p=await prisma.puzzleProject.findFirst({where:{id:req.params.id,ownerId:req.user.id}}); if(!p) throw Object.assign(new Error('Puzzle nicht gefunden'),{status:404}); const progress=await prisma.savedPuzzleState.upsert({ where:{projectId:p.id}, update:{ snapshotJson:JSON.stringify(body.snapshot), progressPercent:body.progressPercent }, create:{ projectId:p.id, ownerId:req.user.id, snapshotJson:JSON.stringify(body.snapshot), progressPercent:body.progressPercent } }); res.json({ progress:{...progress,snapshot:JSON.parse(progress.snapshotJson)} }); }catch(e){next(e);} }
router.put('/:id/progress', saveProgress); router.post('/:id/progress/autosave', saveProgress);
export default router;
