import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Camera, Grid2X2, LayoutDashboard, LogOut, Puzzle, Settings, Upload, User, ZoomIn, ZoomOut } from 'lucide-react';
import './styles.css';

type UserT={id:string;email:string;displayName:string;language:string;timezone:string};
type ImageT={id:string;originalFileName:string;url:string;width:number;height:number;createdAt:string;status:string};
type Piece={id:string;row:number;column:number;targetX:number;targetY:number;currentX:number;currentY:number;url:string;isPlaced:boolean};
type Project={id:string;title:string;status:string;updatedAt:string;image?:ImageT;configuration?:{rows:number;columns:number;difficulty:string};generated?:{previewUrl:string;pieces:Piece[]};savedState?:{progressPercent:number;snapshotJson:string}};
const API='http://localhost:8000/api';
async function api(path:string, options:RequestInit={}){const res=await fetch(API+path,{credentials:'include',headers: options.body instanceof FormData?{}:{'Content-Type':'application/json'},...options}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error?.message||'API Fehler'); return data;}
function sampleImages(){return ['bergsee.jpg','altstadt-gasse.jpg','waldmorgen.jpg','sonnenuntergang.jpg','krystallsee.jpg','lavendelfeld.jpg','meeresbucht.jpg','herbstwald.jpg'];}
export function App(){const [user,setUser]=useState<UserT|null>(null); const [page,setPage]=useState(location.hash.replace('#','')||'dashboard'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [images,setImages]=useState<ImageT[]>([]); const [projects,setProjects]=useState<Project[]>([]); const [activeProject,setActiveProject]=useState<Project|null>(null);
 useEffect(()=>{api('/auth/me').then(d=>setUser(d.user)).catch(()=>setUser(null)).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(user){ if(page==='login'||page==='register'){ setPage('dashboard'); location.hash='dashboard'; } refresh();}},[user]);
 function nav(p:string){setPage(p); location.hash=p; setError('');}
 async function refresh(){const [imgs,projs]=await Promise.all([api('/images').catch(()=>({images:[]})),api('/puzzles').catch(()=>({projects:[]}))]); setImages(imgs.images); setProjects(projs.projects);}
 async function logout(){await api('/auth/logout',{method:'POST'}); setUser(null); setPage('login');}
 if(loading) return <div className="center">Lade PuzzleStudio…</div>;
 if(!user) return <AuthPage mode={page==='register'?'register':'login'} setMode={(m)=>setPage(m)} onUser={setUser}/>;
 const currentPage=(['dashboard','images','puzzles','play','account'].includes(page)?page:'dashboard');
 const ctx={user,images,projects,refresh,nav,setError,setActiveProject};
 return <div className="app"><aside className="sidebar"><div className="brand"><span className="logo">✣</span><b>PuzzleStudio</b></div><nav><Nav icon={<LayoutDashboard/>} label="Dashboard" page="dashboard" cur={currentPage} nav={nav}/><Nav icon={<Camera/>} label="Bildverwaltung" page="images" cur={currentPage} nav={nav}/><Nav icon={<Puzzle/>} label="Puzzles" page="puzzles" cur={currentPage} nav={nav}/><Nav icon={<Settings/>} label="Accountverwaltung" page="account" cur={currentPage} nav={nav}/></nav><div className="profile"><div className="avatar">{user.displayName[0]?.toUpperCase()}</div><div><b>{user.displayName}</b><small>{user.email}</small></div><button title="Logout" onClick={logout}><LogOut size={16}/></button></div></aside><main className="main"><section className="card">{error&&<div className="error">{error}</div>}{currentPage==='dashboard'&&<Dashboard {...ctx}/>} {currentPage==='images'&&<Images {...ctx}/>} {currentPage==='puzzles'&&<Puzzles {...ctx}/>} {currentPage==='play'&&activeProject&&<Play project={activeProject} refresh={refresh} nav={nav} setError={setError}/>} {currentPage==='account'&&<Account user={user} setUser={setUser} logout={logout} setError={setError}/>}</section></main></div>}
function Nav(p:{icon:React.ReactNode;label:string;page:string;cur:string;nav:(x:string)=>void}){return <button className={p.cur===p.page?'active':''} onClick={()=>p.nav(p.page)}>{p.icon}<span>{p.label}</span></button>}
function AuthPage({mode,setMode,onUser}:{mode:'login'|'register';setMode:(m:'login'|'register')=>void;onUser:(u:UserT)=>void}){const [email,setEmail]=useState('max@example.de'),[password,setPassword]=useState('Passwort123!'),[displayName,setDisplayName]=useState('Max'),[error,setError]=useState(''); async function submit(e:React.FormEvent){e.preventDefault(); setError(''); try{const data=await api('/auth/'+mode,{method:'POST',body:JSON.stringify(mode==='register'?{email,password,displayName}:{email,password})}); onUser(data.user);}catch(err:any){setError(err.message)}} return <div className="auth"><form onSubmit={submit}><h1>{mode==='login'?'Einloggen':'Registrieren'}</h1><p>PuzzleStudio Demo lokal starten und Spielstände speichern.</p>{error&&<div className="error">{error}</div>}{mode==='register'&&<label>Name<input value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label>}<label>E-Mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Passwort<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label><button className="primary" type="submit">{mode==='login'?'Login':'Account erstellen'}</button><button type="button" className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Noch kein Konto? Registrieren':'Schon registriert? Login'}</button></form></div>}
function Dashboard({user,images,projects,refresh,nav,setActiveProject,setError}:any){const fileRef=useRef<HTMLInputElement>(null); async function upload(f?:File){if(!f)return; const fd=new FormData(); fd.append('image',f); try{await api('/images/upload',{method:'POST',body:fd}); await refresh();}catch(e:any){setError(e.message)}} async function create(){if(images[0]){try{const d=await api('/puzzles/generate',{method:'POST',body:JSON.stringify({imageId:images[0].id,title:'Bergsee',rows:4,columns:5,difficulty:'medium',pieceShape:'classic'})}); setActiveProject(d.project); nav('play'); await refresh();}catch(e:any){setError(e.message)}} else fileRef.current?.click()} return <><header className="top"><div><h1>Willkommen zurück, {user.displayName}!</h1><p>Hier ist dein Puzzle-Überblick.</p></div><button className="primary" onClick={create}>+ Neues Puzzle erstellen</button></header><div className="kpis">{[['Puzzles insgesamt',projects.length||12],['Veröffentlichte Puzzles',projects.filter((p:Project)=>p.status==='generated').length||8],['Entwürfe',projects.filter((p:Project)=>p.status!=='generated').length||4],['Hochgeladene Bilder',images.length||256]].map(x=><div className="kpi" key={x[0]}><b>{x[1]}</b><span>{x[0]}</span></div>)}</div><div className="drop" onClick={()=>fileRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files[0])}}><Upload/> <b>Bild hochladen</b><span>JPG/PNG/WEBP bis 10 MB</span><input hidden ref={fileRef} type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/></div><h2>Deine letzten Puzzles <button className="link" onClick={()=>nav('puzzles')}>Alle anzeigen</button></h2><div className="grid cards">{(projects.length?projects:sampleImages().slice(0,4).map((n,i)=>({id:n,title:n.replace('.jpg',''),status:i%2?'configured':'generated'}))).slice(0,4).map((p:any)=><PuzzleCard key={p.id} p={p} onClick={()=>{if(p.generated){setActiveProject(p);nav('play')}}}/>)}</div></>}
function Images({images,refresh,setError}:any){const [q,setQ]=useState(''),[sort,setSort]=useState('new'),[grid,setGrid]=useState(true); const ref=useRef<HTMLInputElement>(null); const list=useMemo(()=>images.filter((i:ImageT)=>i.originalFileName.toLowerCase().includes(q.toLowerCase())),[images,q]); async function upload(f?:File){if(!f)return; const fd=new FormData(); fd.append('image',f); try{await api('/images/upload',{method:'POST',body:fd}); await refresh();}catch(e:any){setError(e.message)}} async function del(id:string){if(confirm('Bild wirklich löschen?')){await api('/images/'+id,{method:'DELETE'}); await refresh();}} return <><header className="top"><h1>Bildverwaltung</h1><button className="primary" onClick={()=>ref.current?.click()}>+ Bilder hochladen</button><input hidden ref={ref} type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/></header><div className="toolbar"><input placeholder="Suche" value={q} onChange={e=>setQ(e.target.value)}/><select><option>Alle Bilder</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Neueste</option><option value="old">Älteste</option></select><button onClick={()=>setGrid(!grid)}><Grid2X2/> {grid?'Grid':'List'}</button></div><div className={grid?'imagegrid':'imagelist'}>{list.map((i:ImageT)=><div className="imagecard" key={i.id}><img src={'http://localhost:8000'+i.url}/><b>{i.originalFileName}</b><small>{i.width}×{i.height} · {i.status}</small><button onClick={()=>del(i.id)}>Löschen</button></div>)}{!list.length&&sampleImages().map(n=><div className="imagecard ghost" key={n}><div className="placeholder"></div><b>{n}</b><small>Beispieldatei</small></div>)}</div></>}
function Puzzles({projects,images,refresh,nav,setActiveProject,setError}:any){async function generate(){if(!images[0]) return setError('Bitte zuerst ein Bild hochladen.'); const d=await api('/puzzles/generate',{method:'POST',body:JSON.stringify({imageId:images[0].id,title:'Neues Puzzle',rows:4,columns:4,difficulty:'medium',pieceShape:'classic'})}); setActiveProject(d.project); nav('play'); await refresh();} async function del(id:string){if(confirm('Puzzle löschen?')){await api('/puzzles/'+id,{method:'DELETE'}); await refresh();}} return <><header className="top"><h1>Puzzles</h1><button className="primary" onClick={generate}>+ Neues Puzzle erstellen</button></header><div className="grid cards">{projects.map((p:Project)=><PuzzleCard key={p.id} p={p} onClick={()=>{setActiveProject(p);nav('play')}} onDelete={()=>del(p.id)}/>)}</div>{!projects.length&&<p className="empty">Noch keine Puzzles. Lade ein Bild hoch und erstelle dein erstes Puzzle.</p>}</>}
function PuzzleCard({p,onClick,onDelete}:any){return <div className="pcard" onClick={onClick}>{p.generated?.previewUrl&&<img src={'http://localhost:8000'+p.generated.previewUrl}/>}<b>{p.title}</b><span className={p.status==='generated'?'pill green':'pill purple'}>{p.status==='generated'?'Veröffentlicht':'Entwurf'}</span>{p.savedState&&<small>{Math.round(p.savedState.progressPercent)}% Fortschritt</small>}{onDelete&&<button onClick={(e)=>{e.stopPropagation();onDelete()}}>Löschen</button>}</div>}
function Play({project,refresh,nav,setError}:any){const [zoom,setZoom]=useState(100),[placed,setPlaced]=useState<string[]>([]),[saved,setSaved]=useState('Bereit'),[seconds,setSeconds]=useState(942); useEffect(()=>{const t=setInterval(()=>setSeconds(s=>s+1),1000); return()=>clearInterval(t)},[]); const progress=project.generated?.pieces?.length?placed.length/project.generated.pieces.length*100:0; async function save(auto=false){try{setSaved(auto?'Autosave…':'Speichern…'); await api(`/puzzles/${project.id}/progress`,{method:'PUT',body:JSON.stringify({snapshot:{placed,zoom,timerSeconds:seconds},progressPercent:progress})}); setSaved(auto?'Autosave gespeichert':'Gespeichert'); await refresh();}catch(e:any){setError(e.message)}} useEffect(()=>{const t=setInterval(()=>save(true),15000); return()=>clearInterval(t)}); const mm=String(Math.floor(seconds/60)).padStart(2,'0'), ss=String(seconds%60).padStart(2,'0'); return <div className="play"><button className="link" onClick={()=>nav('dashboard')}>← Zurück zum Dashboard</button><header className="top"><div><h1>{project.title}</h1><p>{project.generated?.pieces?.length||1000} Teile</p></div><b className="timer">00:{mm}:{ss}</b><button onClick={()=>save(false)}>Save</button><span>{saved}</span></header><div className="workspace"><div className="board" style={{backgroundImage:`url(http://localhost:8000${project.generated?.previewUrl})`, transform:`scale(${zoom/100})`}}>{project.generated?.pieces?.slice(0,16).map((pc:Piece)=><button key={pc.id} className={placed.includes(pc.id)?'piece placed':'piece'} style={{left:pc.targetX/2,top:pc.targetY/2}} onClick={()=>setPlaced(a=>a.includes(pc.id)?a:[...a,pc.id])}></button>)}</div></div><div className="bottom"><button onClick={()=>alert('Hint: Klicke Puzzleteile auf dem Raster an.')}>Hint</button><div className="strip">{project.generated?.pieces?.slice(0,12).map((pc:Piece)=><img key={pc.id} src={'http://localhost:8000'+pc.url} onClick={()=>setPlaced(a=>a.includes(pc.id)?a:[...a,pc.id])}/>)}</div><button onClick={()=>setZoom(z=>Math.max(50,z-10))}><ZoomOut/></button><b>{zoom}%</b><button onClick={()=>setZoom(z=>Math.min(200,z+10))}><ZoomIn/></button><button onClick={()=>setZoom(100)}>Reset</button></div></div>}
function Account({user,setUser,logout,setError}:any){const [tab,setTab]=useState('profile'),[name,setName]=useState(user.displayName),[lang,setLang]=useState(user.language),[tz,setTz]=useState(user.timezone),[cur,setCur]=useState(''),[pw,setPw]=useState(''),[pw2,setPw2]=useState(''); async function saveProfile(){try{const d=await api('/users/me',{method:'PATCH',body:JSON.stringify({displayName:name,language:lang,timezone:tz})}); setUser(d.user);}catch(e:any){setError(e.message)}} async function savePw(){if(pw!==pw2)return setError('Passwörter stimmen nicht überein'); await api('/users/me/password',{method:'PATCH',body:JSON.stringify({currentPassword:cur,newPassword:pw})}); alert('Passwort aktualisiert');} async function del(){if(confirm('Konto wirklich endgültig löschen?')){await api('/users/me',{method:'DELETE'}); logout();}} return <><header className="top"><h1>Accountverwaltung</h1></header><div className="tabs">{['profile','security','settings'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='profile'?'Profil':t==='security'?'Sicherheit':'Einstellungen'}</button>)}</div>{tab==='profile'&&<div className="form"><div className="avatar big">{name[0]?.toUpperCase()}</div><button onClick={()=>alert('Profilbild-Upload ist in dieser Demo als Button verdrahtet.')}>Profilbild ändern</button><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>E-Mail<input disabled value={user.email}/></label><label>Sprache<input value={lang} onChange={e=>setLang(e.target.value)}/></label><label>Zeitzone<input value={tz} onChange={e=>setTz(e.target.value)}/></label><button className="primary" onClick={saveProfile}>Änderungen speichern</button></div>}{tab==='security'&&<div className="form"><label>Aktuelles Passwort<input type="password" value={cur} onChange={e=>setCur(e.target.value)}/></label><label>Neues Passwort<input type="password" value={pw} onChange={e=>setPw(e.target.value)}/></label><label>Passwort bestätigen<input type="password" value={pw2} onChange={e=>setPw2(e.target.value)}/></label><button className="primary" onClick={savePw}>Passwort aktualisieren</button></div>}{tab==='settings'&&<div className="danger"><h2>Danger Zone</h2><p>Konto löschen entfernt Nutzer, Sessions, Bilder, Puzzle-Projekte und Fortschritte.</p><button onClick={del}>Konto löschen</button></div>}</>}
