import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Camera, Grid2X2, LayoutDashboard, LogOut, Puzzle, Settings, Upload, ZoomIn, ZoomOut } from 'lucide-react';
import './styles.css';

type UserT = { id: string; email: string; displayName: string; language: string; timezone: string };
type ImageT = { id: string; ownerId: string; originalFileName: string; url: string; width: number; height: number; createdAt: string; status: string };
type Piece = { id: string; row: number; column: number; targetX: number; targetY: number; currentX: number; currentY: number; url: string; isPlaced: boolean };
type Project = { id: string; ownerId: string; title: string; status: string; visibility: 'private' | 'public'; updatedAt: string; image?: ImageT; configuration?: { rows: number; columns: number; difficulty: string }; generated?: { previewUrl: string; pieces: Piece[] }; savedState?: { progressPercent: number; snapshotJson: string } };
type PieceState = { x: number; y: number; rotation: number; placed: boolean };

const API = 'http://localhost:8000/api';
async function api(path: string, options: RequestInit = {}) {
  const res = await fetch(API + path, { credentials: 'include', headers: options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }, ...options });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error?.message || 'API Fehler');
  return data;
}
function parseSnapshot(project: Project) {
  try { return project.savedState?.snapshotJson ? JSON.parse(project.savedState.snapshotJson) : {}; } catch { return {}; }
}

export function App() {
  const [user, setUser] = useState<UserT | null>(null);
  const [page, setPage] = useState(location.hash.replace('#', '') || 'dashboard');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [images, setImages] = useState<ImageT[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [activeProject, setActiveProject] = useState<Project | null>(null);

  useEffect(() => { api('/auth/me').then(d => setUser(d.user)).catch(() => setUser(null)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (user) { if (page === 'login' || page === 'register') { setPage('dashboard'); location.hash = 'dashboard'; } void refresh(); } }, [user]);
  async function refresh() { const [imgs, projs] = await Promise.all([api('/images').catch(() => ({ images: [] })), api('/puzzles').catch(() => ({ projects: [] }))]); setImages(imgs.images); setProjects(projs.projects); }
  function nav(p: string) { setPage(p); location.hash = p; setError(''); }
  async function logout() { await api('/auth/logout', { method: 'POST' }); setUser(null); setPage('login'); }

  if (loading) return <div className="center">Lade PuzzleStudio…</div>;
  if (!user) return <AuthPage mode={page === 'register' ? 'register' : 'login'} setMode={setPage} onUser={setUser} />;
  const currentPage = ['dashboard', 'images', 'puzzles', 'play', 'account'].includes(page) ? page : 'dashboard';
  const ctx = { user, images, projects, refresh, nav, setError, setActiveProject };
  return <div className="app"><aside className="sidebar"><div className="brand"><span className="logo">✣</span><b>PuzzleStudio</b></div><nav><Nav icon={<LayoutDashboard />} label="Dashboard" page="dashboard" cur={currentPage} nav={nav} /><Nav icon={<Camera />} label="Bildverwaltung" page="images" cur={currentPage} nav={nav} /><Nav icon={<Puzzle />} label="Puzzles" page="puzzles" cur={currentPage} nav={nav} /><Nav icon={<Settings />} label="Accountverwaltung" page="account" cur={currentPage} nav={nav} /></nav><div className="profile"><div className="avatar">{user.displayName[0]?.toUpperCase()}</div><div><b>{user.displayName}</b><small>{user.email}</small></div><button title="Logout" onClick={logout}><LogOut size={16} /></button></div></aside><main className="main"><section className="card">{error && <div className="error">{error}</div>}{currentPage === 'dashboard' && <Dashboard {...ctx} />}{currentPage === 'images' && <Images {...ctx} />}{currentPage === 'puzzles' && <Puzzles {...ctx} />}{currentPage === 'play' && activeProject && <Play project={activeProject} refresh={refresh} nav={nav} setError={setError} />}{currentPage === 'account' && <Account user={user} setUser={setUser} logout={logout} setError={setError} />}</section></main></div>;
}
function Nav(p: { icon: React.ReactNode; label: string; page: string; cur: string; nav: (x: string) => void }) { return <button className={p.cur === p.page ? 'active' : ''} onClick={() => p.nav(p.page)}>{p.icon}<span>{p.label}</span></button>; }

function AuthPage({ mode, setMode, onUser }: { mode: string; setMode: (m: string) => void; onUser: (u: UserT) => void }) {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [displayName, setDisplayName] = useState(''), [error, setError] = useState('');
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); try { const data = await api('/auth/' + mode, { method: 'POST', body: JSON.stringify(mode === 'register' ? { email, password, displayName } : { email, password }) }); onUser(data.user); } catch (err: any) { setError(err.message); } }
  return <div className="auth"><form onSubmit={submit}><h1>{mode === 'login' ? 'Einloggen' : 'Registrieren'}</h1><p>Bitte gib deine eigenen Zugangsdaten ein.</p>{error && <div className="error">{error}</div>}{mode === 'register' && <label>Name<input value={displayName} onChange={e => setDisplayName(e.target.value)} autoComplete="name" /></label>}<label>E-Mail<input value={email} onChange={e => setEmail(e.target.value)} type="email" autoComplete="email" /></label><label>Passwort<input value={password} onChange={e => setPassword(e.target.value)} type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /></label><button className="primary" type="submit">{mode === 'login' ? 'Login' : 'Account erstellen'}</button><button type="button" className="link" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Noch kein Konto? Registrieren' : 'Schon registriert? Login'}</button></form></div>;
}

function CreatePuzzlePanel({ images, refresh, nav, setActiveProject, setError }: any) {
  const [imageId, setImageId] = useState(images[0]?.id ?? ''), [title, setTitle] = useState(''), [rows, setRows] = useState(4), [columns, setColumns] = useState(4), [visibility, setVisibility] = useState<'private' | 'public'>('private');
  useEffect(() => { if (!imageId && images[0]) setImageId(images[0].id); }, [images, imageId]);
  async function create() { if (!imageId) return setError('Bitte zuerst ein Bild hochladen.'); try { const d = await api('/puzzles/generate', { method: 'POST', body: JSON.stringify({ imageId, title: title || 'Neues Puzzle', rows, columns, difficulty: 'medium', pieceShape: 'classic', visibility }) }); setActiveProject(d.project); await refresh(); nav('play'); } catch (e: any) { setError(e.message); } }
  return <div className="creator"><h2>Neues Puzzle erstellen</h2><select value={imageId} onChange={e => setImageId(e.target.value)}>{images.map((i: ImageT) => <option key={i.id} value={i.id}>{i.originalFileName}</option>)}</select><input placeholder="Puzzle-Titel" value={title} onChange={e => setTitle(e.target.value)} /><label>Zeilen<input type="number" min={2} max={20} value={rows} onChange={e => setRows(Number(e.target.value))} /></label><label>Spalten<input type="number" min={2} max={20} value={columns} onChange={e => setColumns(Number(e.target.value))} /></label><select value={visibility} onChange={e => setVisibility(e.target.value as 'private' | 'public')}><option value="private">Nur für meinen Account</option><option value="public">Für alle Nutzer verfügbar</option></select><button className="primary" onClick={create}>Puzzle generieren</button></div>;
}

function Dashboard({ user, images, projects, refresh, nav, setActiveProject, setError }: any) {
  const fileRef = useRef<HTMLInputElement>(null); const own = projects.filter((p: Project) => p.ownerId === user.id); const published = own.filter((p: Project) => p.visibility === 'public').length; const drafts = own.filter((p: Project) => p.status !== 'generated').length;
  async function upload(f?: File) { if (!f) return; const fd = new FormData(); fd.append('image', f); try { await api('/images/upload', { method: 'POST', body: fd }); await refresh(); } catch (e: any) { setError(e.message); } }
  return <><header className="top"><div><h1>Willkommen zurück, {user.displayName}!</h1><p>Hier ist dein echter Puzzle-Überblick aus der Datenbank.</p></div><button className="primary" onClick={() => images.length ? document.getElementById('creator')?.scrollIntoView({ behavior: 'smooth' }) : fileRef.current?.click()}>+ Neues Puzzle erstellen</button></header><div className="kpis">{[['Puzzles insgesamt', own.length], ['Für alle Nutzer', published], ['Entwürfe', drafts], ['Hochgeladene Bilder', images.length]].map(x => <div className="kpi" key={x[0]}><b>{x[1]}</b><span>{x[0]}</span></div>)}</div><div className="drop" onClick={() => fileRef.current?.click()} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); void upload(e.dataTransfer.files[0]); }}><Upload /><b>Bild hochladen</b><span>JPG/PNG/WEBP bis 10 MB</span><input hidden ref={fileRef} type="file" accept="image/*" onChange={e => upload(e.target.files?.[0])} /></div>{images.length > 0 && <div id="creator"><CreatePuzzlePanel images={images} refresh={refresh} nav={nav} setActiveProject={setActiveProject} setError={setError} /></div>}<h2>Deine letzten Puzzles <button className="link" onClick={() => nav('puzzles')}>Alle anzeigen</button></h2><div className="grid cards">{own.slice(0, 4).map((p: Project) => <PuzzleCard key={p.id} p={p} currentUserId={user.id} onClick={() => { setActiveProject(p); nav('play'); }} />)}</div>{own.length === 0 && <p className="empty">Noch keine eigenen Puzzles. Lade ein Bild hoch und erstelle dein erstes Puzzle.</p>}</>;
}

function Images({ images, refresh, setError }: any) {
  const [q, setQ] = useState(''), [sort, setSort] = useState('new'), [grid, setGrid] = useState(true); const ref = useRef<HTMLInputElement>(null);
  const list = useMemo(() => images.filter((i: ImageT) => i.originalFileName.toLowerCase().includes(q.toLowerCase())).sort((a: ImageT, b: ImageT) => sort === 'new' ? Date.parse(b.createdAt) - Date.parse(a.createdAt) : Date.parse(a.createdAt) - Date.parse(b.createdAt)), [images, q, sort]);
  async function upload(f?: File) { if (!f) return; const fd = new FormData(); fd.append('image', f); try { await api('/images/upload', { method: 'POST', body: fd }); await refresh(); } catch (e: any) { setError(e.message); } }
  async function del(id: string) { if (confirm('Bild wirklich löschen?')) { await api('/images/' + id, { method: 'DELETE' }); await refresh(); } }
  return <><header className="top"><h1>Bildverwaltung</h1><button className="primary" onClick={() => ref.current?.click()}>+ Bilder hochladen</button><input hidden ref={ref} type="file" accept="image/*" onChange={e => upload(e.target.files?.[0])} /></header><div className="toolbar"><input placeholder="Suche" value={q} onChange={e => setQ(e.target.value)} /><select><option>Eigene Bilder</option></select><select value={sort} onChange={e => setSort(e.target.value)}><option value="new">Neueste</option><option value="old">Älteste</option></select><button onClick={() => setGrid(!grid)}><Grid2X2 /> {grid ? 'Grid' : 'List'}</button></div><div className={grid ? 'imagegrid' : 'imagelist'}>{list.map((i: ImageT) => <div className="imagecard" key={i.id}><a href={'http://localhost:8000' + i.url} target="_blank"><img src={'http://localhost:8000' + i.url} /></a><b>{i.originalFileName}</b><small>{i.width}×{i.height} · {i.status}</small><button onClick={() => del(i.id)}>Löschen</button></div>)}</div>{!list.length && <p className="empty">Keine Beispielbilder mehr: Hier erscheinen nur echte Bilder aus deiner Datenbank.</p>}</>;
}

function Puzzles({ user, projects, images, refresh, nav, setActiveProject, setError }: any) {
  async function del(id: string) { if (confirm('Puzzle löschen?')) { await api('/puzzles/' + id, { method: 'DELETE' }); await refresh(); } }
  return <><header className="top"><h1>Puzzles</h1></header>{images.length > 0 && <CreatePuzzlePanel images={images} refresh={refresh} nav={nav} setActiveProject={setActiveProject} setError={setError} />}<div className="grid cards">{projects.map((p: Project) => <PuzzleCard key={p.id} p={p} currentUserId={user.id} onClick={() => { setActiveProject(p); nav('play'); }} onDelete={p.ownerId === user.id ? () => del(p.id) : undefined} />)}</div>{!projects.length && <p className="empty">Noch keine Puzzles. Lade ein Bild hoch und erstelle dein erstes Puzzle.</p>}</>;
}
function PuzzleCard({ p, onClick, onDelete, currentUserId }: any) { return <div className="pcard" onClick={onClick}>{p.generated?.previewUrl && <img src={'http://localhost:8000' + p.generated.previewUrl} />}<b>{p.title}</b><span className={p.visibility === 'public' ? 'pill green' : 'pill purple'}>{p.visibility === 'public' ? 'Für alle Nutzer' : 'Privat'}</span><small>{p.ownerId === currentUserId ? 'Eigenes Puzzle' : 'Öffentliches Puzzle'} · {Math.round(p.savedState?.progressPercent ?? 0)}% Fortschritt</small>{onDelete && <button onClick={(e) => { e.stopPropagation(); onDelete(); }}>Löschen</button>}</div>; }

function Play({ project, refresh, nav, setError }: any) {
  const pieces = project.generated?.pieces ?? []; const cfg = project.configuration ?? { rows: 4, columns: 4 }; const pieceW = 900 / cfg.columns, pieceH = 600 / cfg.rows; const snap = parseSnapshot(project);
  const [zoom, setZoom] = useState(Math.round((snap.zoom ?? 1) * 100)); const [seconds, setSeconds] = useState(snap.timerSeconds ?? 0); const [saved, setSaved] = useState('Bereit'); const [selected, setSelected] = useState<string | null>(snap.selectedPieceId ?? null); const drag = useRef<{ id: string; dx: number; dy: number } | null>(null);
  const [pieceStates, setPieceStates] = useState<Record<string, PieceState>>(() => Object.fromEntries(pieces.map((p: Piece) => [p.id, { x: snap.pieces?.[p.id]?.x ?? p.currentX, y: snap.pieces?.[p.id]?.y ?? p.currentY, rotation: snap.pieces?.[p.id]?.rotation ?? 0, placed: snap.pieces?.[p.id]?.placed ?? false }] as const)));
  useEffect(() => { const t = setInterval(() => setSeconds((s: number) => s + 1), 1000); return () => clearInterval(t); }, []);
  const placedCount = Object.values(pieceStates).filter(p => p.placed).length; const progress = pieces.length ? placedCount / pieces.length * 100 : 0;
  function normalize(r: number) { return ((r % 360) + 360) % 360; }
  function updatePiece(id: string, patch: Partial<PieceState>) { setPieceStates(s => ({ ...s, [id]: { ...s[id], ...patch } })); }
  function onPointerDown(e: React.PointerEvent, id: string) { const st = pieceStates[id]; setSelected(id); drag.current = { id, dx: e.clientX - st.x, dy: e.clientY - st.y }; (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId); }
  function onPointerMove(e: React.PointerEvent) { if (!drag.current) return; const id = drag.current.id; updatePiece(id, { x: e.clientX - drag.current.dx, y: e.clientY - drag.current.dy, placed: false }); }
  function onPointerUp() { if (!drag.current) return; const id = drag.current.id; const pc = pieces.find((p: Piece) => p.id === id); const st = pieceStates[id]; const rotOk = normalize(st.rotation) <= 12 || normalize(st.rotation) >= 348; const near = pc && Math.abs(st.x - pc.targetX) < 35 && Math.abs(st.y - pc.targetY) < 35; if (pc && near && rotOk) updatePiece(id, { x: pc.targetX, y: pc.targetY, rotation: 0, placed: true }); drag.current = null; }
  function rotateSelected(deltaY: number) { if (!selected) return; updatePiece(selected, { rotation: (pieceStates[selected].rotation ?? 0) + (deltaY < 0 ? -15 : 15), placed: false }); }
  async function save(auto = false) { try { setSaved(auto ? 'Autosave…' : 'Speichern…'); await api(`/puzzles/${project.id}/progress`, { method: 'PUT', body: JSON.stringify({ snapshot: { pieces: pieceStates, zoom: zoom / 100, timerSeconds: seconds, selectedPieceId: selected }, progressPercent: progress }) }); setSaved(auto ? 'Autosave gespeichert' : 'Gespeichert'); await refresh(); } catch (e: any) { setError(e.message); } }
  useEffect(() => { const t = setInterval(() => save(true), 20000); return () => clearInterval(t); });
  const mm = String(Math.floor(seconds / 60)).padStart(2, '0'), ss = String(seconds % 60).padStart(2, '0');
  return <div className="play"><button className="link" onClick={() => nav('dashboard')}>← Zurück zum Dashboard</button><header className="top"><div><h1>{project.title}</h1><p>{pieces.length} Teile · {project.visibility === 'public' ? 'Für alle Nutzer' : 'Privat'} · Scrollrad: hoch = links drehen, runter = rechts drehen</p></div><b className="timer">00:{mm}:{ss}</b><button onClick={() => save(false)}>Save</button><span>{saved}</span></header><div className="workspace" onWheel={e => { e.preventDefault(); rotateSelected(e.deltaY); }}><div className="target" style={{ backgroundImage: `url(http://localhost:8000${project.generated?.previewUrl})`, transform: `scale(${zoom / 100})` }} />{pieces.map((pc: Piece) => { const st = pieceStates[pc.id]; return <img key={pc.id} src={'http://localhost:8000' + pc.url} className={(selected === pc.id ? 'dragpiece selected' : 'dragpiece') + (st?.placed ? ' placed' : '')} style={{ left: st?.x ?? pc.currentX, top: st?.y ?? pc.currentY, width: pieceW, height: pieceH, transform: `rotate(${st?.rotation ?? 0}deg) scale(${zoom / 100})` }} onPointerDown={e => onPointerDown(e, pc.id)} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onDoubleClick={() => updatePiece(pc.id, { rotation: 0 })} title="Anklicken/ziehen; Scrollrad rotiert das ausgewählte Teil" />; })}</div><div className="bottom"><button onClick={() => alert('Hint: Ziehe ein Teil nahe an seine Position. Wenn es richtig liegt und nicht verdreht ist, rastet es ein.')}>Hint</button><div className="strip">{pieces.slice(0, 16).map((pc: Piece) => <img key={pc.id} src={'http://localhost:8000' + pc.url} className={selected === pc.id ? 'mini active' : 'mini'} onClick={() => setSelected(pc.id)} />)}</div><button onClick={() => setZoom(z => Math.max(50, z - 10))}><ZoomOut /></button><b>{zoom}%</b><button onClick={() => setZoom(z => Math.min(180, z + 10))}><ZoomIn /></button><button onClick={() => setZoom(100)}>Reset</button></div></div>;
}

function Account({ user, setUser, logout, setError }: any) { const [tab, setTab] = useState('profile'), [name, setName] = useState(user.displayName), [lang, setLang] = useState(user.language), [tz, setTz] = useState(user.timezone), [cur, setCur] = useState(''), [pw, setPw] = useState(''), [pw2, setPw2] = useState(''); async function saveProfile() { try { const d = await api('/users/me', { method: 'PATCH', body: JSON.stringify({ displayName: name, language: lang, timezone: tz }) }); setUser(d.user); } catch (e: any) { setError(e.message); } } async function savePw() { if (pw !== pw2) return setError('Passwörter stimmen nicht überein'); await api('/users/me/password', { method: 'PATCH', body: JSON.stringify({ currentPassword: cur, newPassword: pw }) }); alert('Passwort aktualisiert'); } async function del() { if (confirm('Konto wirklich endgültig löschen?')) { await api('/users/me', { method: 'DELETE' }); logout(); } } return <><header className="top"><h1>Accountverwaltung</h1></header><div className="tabs">{['profile', 'security', 'settings'].map(t => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t === 'profile' ? 'Profil' : t === 'security' ? 'Sicherheit' : 'Einstellungen'}</button>)}</div>{tab === 'profile' && <div className="form"><div className="avatar big">{name[0]?.toUpperCase()}</div><button onClick={() => alert('Profilbild-Upload ist als Button verdrahtet.')}>Profilbild ändern</button><label>Name<input value={name} onChange={e => setName(e.target.value)} /></label><label>E-Mail<input disabled value={user.email} /></label><label>Sprache<input value={lang} onChange={e => setLang(e.target.value)} /></label><label>Zeitzone<input value={tz} onChange={e => setTz(e.target.value)} /></label><button className="primary" onClick={saveProfile}>Änderungen speichern</button></div>}{tab === 'security' && <div className="form"><label>Aktuelles Passwort<input type="password" value={cur} onChange={e => setCur(e.target.value)} /></label><label>Neues Passwort<input type="password" value={pw} onChange={e => setPw(e.target.value)} /></label><label>Passwort bestätigen<input type="password" value={pw2} onChange={e => setPw2(e.target.value)} /></label><button className="primary" onClick={savePw}>Passwort aktualisieren</button></div>}{tab === 'settings' && <div className="danger"><h2>Danger Zone</h2><p>Konto löschen entfernt Nutzer, Sessions, Bilder, Puzzle-Projekte und Fortschritte.</p><button onClick={del}>Konto löschen</button></div>}</>; }
